# ==============================================================================
# GT Monitoramento 2025
# Variáveis Globais do Projeto
# Arquivo: group_vars/all.yml
# Descrição: Este arquivo contém variáveis globais utilizadas nos roles:
#             - vm_config_setup (roles/vm_config_setup)
#             - zabbix_proxy (roles/zabbix_proxy)
#             - zabbix_agent (roles/zabbix_agent)
#             - zabbix_api_proxy (roles/zabbix_api_proxy)
#             - zabbix_api_agent (roles/zabbix_api_agent)
# Feito por: GT de Monitoramento 2025
# ==============================================================================

# ==============================================================================
# Seção 0: Variáveis Zabbix Proxy x Zabbix Server
# ==============================================================================
# Descrição: Variáveis que controlam a comunicação com o Zabbix Server central
# e que são usadas por múltiplos roles (proxy, agent, etc).
# ==============================================================================

# Endereço IP do Zabbix Server Central.
zabbix_server_ip: "192.168.0.208"


# Lista de IPs dos servidores Zabbix que os agentes podem usar para 
# checagens ativas (ServerActive no agent).
zabbix_active_server_ips:
  - "192.168.0.208"

# URL do Zabbix Server
zabbix_server_url: "http://192.168.0.208/zabbix"

# Token de autenticação da API do Zabbix.

zabbix_api_token: "1001461b05b80291e23945d00ec126ab8f147da858e09ea9c2cf6ed04fb87ddd" # necessário colocar num vault

# Proxy: enviar PSK/Identity para o Server quando TLS=PSK?
# - true  = envia PSK e Identity na chamada proxy.update via API.
# - false = não envia nada (identity/psk só no proxy.conf local).
# 
# Recomendado deixar true para manter o server e o proxy alinhados.
zabbix_register_proxy_psk_to_server: true

# ==============================================================================
# Seção I: Configurações de Versão e Repositório Zabbix
# ==============================================================================
# OBS:
# Caso seja alterada a versão, é necessário verificar a compatibilidade dos pacotes,
# pois a instalação pode falhar se houver incompatibilidades.
# Se o SO for alterado, também é necessário alterar o esquema da instalação, e 
# possivelmente o esquema da configuração da rede.
# ==============================================================================
zabbix_version: "7.2"
zabbix_repo_file: "zabbix-release_latest_7.2+debian12_all.deb"
zabbix_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/{{ zabbix_repo_file }}"
zabbix_proxy_package: "zabbix-proxy-sqlite3=1:7.2.7-1+debian12"
zabbix_agent_package: "zabbix-agent2=1:7.2.7-1+debian12"
zabbix_agent_service_name: "zabbix-agent2"

# ==============================================================================
# --- Seção II: Configurações de Rede ---
# ==============================================================================
# Variaveis relacionadas: 
#   - group_vars/pops_configs/{{ location_code }}.yml
#
# OBS: Caso o sistema operacional for alterado, é necessário alterar o esquema 
# de configuração de rede em net_security/templates/interfaces.j2
# e também em Configuração de Rede em roles/net_security/tasks/main.yml.
# ==============================================================================
pop_network_addresses:
  - "{{ pop_network_ipv4_address }}"
  - "{{ pop_network_ipv6_address }}"
pop_network_nameservers: "{{ pop_network_dns_list }}"
pop_network_routes:
  - to: default
    via: "{{ pop_network_ipv4_gateway }}"
    metric: 50
  - to: default
    via: "{{ pop_network_ipv6_gateway }}"

# ==============================================================================
# --- Seção III: Configurações do Zabbix Proxy ---
# ==============================================================================
# Role de execução: roles/zabbix_proxy/tasks/main.yml
# Templates relacionados:
#   - roles/zabbix_proxy/templates/zabbix_proxy.conf.j2
# ==============================================================================
# Referências:
# https://git.rnp.br/gt-monitoramento/poc-monitoramento/-/blob/44887513e9a8aeb02d7203d7bacc2a7decf8515b/config-zabbix-exemplo/zabbix_proxy.conf
# https://gist.github.com/zunkree/7385258
# ==============================================================================
### PROXY MODE
zabbix_proxy_mode: 0
#ProxyMode
#The proxy operating mode.
#0 - proxy in the active mode
#1 - proxy in the passive mode
# Default: 0
#Range: 0-1
# Fonte: https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_proxy

zabbix_proxy_buffermode: "hybrid"
zabbix_proxy_memory_buffer_size: "256M"
zabbix_proxy_proxybuffer: 0

### PROXY SERVICE
zabbix_server_port_for_proxy: 10051          
zabbix_proxy_listenip: "0.0.0.0"
zabbix_proxy_ip: "{{ pop_network_ipv4_address | split('/') | first }}"
zabbix_proxy_pidfile: "/run/zabbix/zabbix_proxy.pid"
zabbix_proxy_socket_dir: "/run/zabbix"

### PROCESSES
zabbix_proxy_startpollers: 550
zabbix_proxy_startpreprocessors: 40
zabbix_proxy_startpollersunreachable: 60
zabbix_proxy_starthistorypollers: 10 # comentado em zabbix_proxy.conf.j2
zabbix_proxy_starttrappers: 10
zabbix_proxy_startpingers: 100
zabbix_proxy_startdiscoverers: 100
zabbix_proxy_starthttpollers: 10
zabbix_proxy_startsnmppollers: 50
zabbix_proxy_startagentpollers: 50
zabbix_proxy_startdbsyncers: 4
zabbix_proxy_startipmipollers: 1
zabbix_proxy_startvmwarecollectors: 1

### CACHE
zabbix_proxy_cachesize: 512M
zabbix_proxy_historycachesize: 64M
zabbix_proxy_historyindexcachesize: 32M

### TLS
zabbix_proxy_tls_connect: 1   # PSK (cliente -> server)
zabbix_proxy_tls_accept: 2    # PSK (proxy aceita conexões PSK)
zabbix_proxy_psk_identity: "{{ zabbix_proxy_hostname }}-psk"
zabbix_proxy_psk_file: "/etc/zabbix/psk/{{ zabbix_proxy_hostname }}.psk"


# nota 
#Na API do Zabbix, os valores são inteiros:
# tls_connect
#   1 → PSK
#   2 → Certificado
# tls_accept (bitmask, pode somar valores)
#   1 → PSK
#   2 → Certificado
#   4 → Sem criptografia

### LOG
zabbix_proxy_logfile: "/var/log/zabbix/zabbix_proxy.log"
zabbix_proxy_logtype: "file"
zabbix_proxy_logfile_size: 5
zabbix_proxy_debug_level: 1

#### LOCAL DATABASE
zabbix_proxy_dbname: "/var/lib/zabbix/zabbix_proxy.db" # discordo de DBName=/tmp/zabbix_proxy.db, porque se a vm rebootar, esse arquivo será excluido
zabbix_proxy_offline_buffer: 12

### TIMERS
HeartbeatFrequency: 60 # comentado em zabbix_proxy.conf.j2
zabbix_proxy_config_frequency: 60
zabbix_proxy_datasender_frequency: 1
zabbix_proxy_housekeeping_frequency: 1
zabbix_proxy_timeout: 15
zabbix_proxy_trappertimeout: 300
zabbix_proxy_unreachable_period: 45
zabbix_proxy_unavailable_delay: 60
zabbix_proxy_unreachable_delay: 15

### FPING
zabbix_proxy_fping_location: "/usr/bin/fping"
zabbix_proxy_fping6_location: "/usr/bin/fping6"

### REMOTE COMMANDS
zabbix_proxy_enable_remote_commands: 0
zabbix_proxy_log_remote_commands: 0

### DATABASE COMPATIBILITY
zabbix_proxy_allow_unsupported_db: 0

### SSH
zabbix_proxy_ssh_key_location: "/etc/zabbix/ssh_keys/.ssh"
# ==============================================================================
# --- Seção IV: Configurações do Zabbix Agent ---
# ==============================================================================
# Role de execução: roles/zabbix_agent/tasks/main.yml
# Templates relacionados:
#   - roles/zabbix_agent/templates/zabbix_agent2.conf.j2
# ==============================================================================
# Referências:
# https://git.rnp.br/gt-monitoramento/poc-monitoramento/-/blob/44887513e9a8aeb02d7203d7bacc2a7decf8515b/config-zabbix-exemplo/zabbix_agent2.conf
# https://gist.github.com/devops-school/429adf956abbc3ddaf2420260d378a0c
# ==============================================================================

# --- GERAL ---
zabbix_agent_pidfile: "/run/zabbix/zabbix_agent2.pid"  # arquivos /tmp sao apagados quando o sistema reinicia
zabbix_agent_logtype: "file" 
zabbix_agent_logfile: "/var/log/zabbix/zabbix_agent2.log"
zabbix_agent_logfile_size: 5
zabbix_agent_debug_level: 1
zabbix_agent_source_ip: "{{ pop_network_ipv4_address | split('/') | first }}"

# --- PASSIVE CHECKS ---
zabbix_agent_server: "{{ zabbix_server_ip }}"
zabbix_agent_listenport: 10050

### ACTIVE CHECKS
zabbix_agent_serveractive_list: "{{ zabbix_active_server_ips }}"
zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
zabbix_agent_refresh_active_checks: 300
zabbix_agent_buffer_send: 10
zabbix_agent_buffer_size: 100
zabbix_agent_enable_persistent_buffering: 0
zabbix_agent_persistent_buffer_period: 1h 
zabbix_agent_persistent_buffer_file: "/var/lib/zabbix/agent2/persistent_buffer" # cometenado no zabbix_agent2.conf.j2

### ADVANCED
zabbix_agent_include_dir: "/etc/zabbix/zabbix_agent2.d/*.conf"
zabbix_agent_timeout: 30
zabbix_agent_unsafe_user_parameters: 0 # cometenado no zabbix_agent2.conf.j2
zabbix_agent_control_socket: "/tmp/agent.sock"

### TLS
zabbix_agent_tls_connect: "psk"
zabbix_agent_tls_accept: "psk"
zabbix_agent_psk_identity: "{{ zabbix_agent_hostname }}-psk-agent"
zabbix_agent_psk_file: "/etc/zabbix/psk/{{ zabbix_agent_hostname }}-agent.psk"

### PLUGINS
zabbix_agent_plugins_log_max_lines: 20
zabbix_agent_plugins_docker_endpoint: "unix:///var/run/docker.sock"
zabbix_agent_plugins_docker_timeout: 20

# ==============================================================================
# --- Seção V: Segurança --- | Ainda necessário verificar 
# ==============================================================================
# Role de execução: roles/network_security/tasks/main.yml
# Templates relacionados:
#   - roles/network_security/templates/sshd_config.j2
#   - roles/network_security/templates/ssh.config.j2 -> Fail2ban
# ==============================================================================

# --- Fail2Ban ---
fail2ban_sshd_port: "{{ ssh_port }}"
fail2ban_maxretry: 10
fail2ban_findtime: 10m
fail2ban_bantime: 24h
fail2ban_ignore_ips:
  - "127.0.0.1/8"
  - "{{ pop_network_ipv4_gateway }}"
  - "{{ zabbix_active_server_ips }}"
  - "{{ pop_network_addresses }}"

ufw_rules:
  # SSH - Gateway
  - rule: allow
    from: ["{{ pop_network_ipv4_gateway }}"]
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH - Gateway IPv4"
    direction: in

  # SSH - POP
  - rule: allow
    from: "{{ pop_network_addresses }}"
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH - IPs do POP"
    direction: in

  # Zabbix - Gateway
  - rule: allow
    from: ["{{ pop_network_ipv4_gateway }}"]
    port: 10050
    proto: tcp
    comment: "Zabbix Agent - Gateway"
    direction: in

  - rule: allow
    from: ["{{ pop_network_ipv4_gateway }}"]
    port: 10051
    proto: tcp
    comment: "Zabbix Proxy - Gateway"
    direction: in

  # Zabbix - Active Servers
  - rule: allow
    from: "{{ zabbix_active_server_ips }}"
    port: 10050
    proto: tcp
    comment: "Zabbix Agent - Active Servers"
    direction: in

  - rule: allow
    from: "{{ zabbix_active_server_ips }}"
    port: 10051
    proto: tcp
    comment: "Zabbix Proxy - Active Servers"
    direction: in

# ==============================================================================
# Seção VI: Configurações de Registro de Host na API
# ==============================================================================
# Grupos de hosts para associar o Agent no Zabbix Server.
zabbix_agent_hostgroups:
  - "Linux servers"
  - "Zabbix proxies"

# Templates para associar ao Agent no Zabbix Server.
zabbix_agent_templates:
  - "Linux by Zabbix agent"
