# ansible/inventory/hosts.yml
all:
  children:
    proxies:
      # =========================
      # Defaults globais (âncora)
      # =========================
      vars: &proxy_defaults
        ansible_user: admin
        ansible_ssh_private_key_file: ansible/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
        # 1º run pode usar 22; depois mude para 22222 se sua role trocar a porta
        ansible_port: 22
        # Se precisar de bastion/jump (opcional):
        # ansible_ssh_common_args: "-o ProxyJump=bastion@bastion.seu.dominio:22"
        # ou para 1º run sem known_hosts:
        # ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

        # =============================
        # Perfis de configuração (anchors)
        # =============================
        profiles:
          pop_ce: &profile_pop_ce
            profile: pop_ce
            # rede (exemplo; ajuste se necessário)
            network_interface: "enX1"
            network_ipv4_address: "192.168.0.17/24"
            network_ipv4_netmask: "255.255.255.0"
            network_ipv4_gateway: "192.168.0.9"
            network_ipv6_address: ""
            network_ipv6_gateway: ""
            network_dns_list: ["200.129.0.41","200.129.0.42"]

          as_angolacables: &profile_as_angolacables
            profile: as_angolacables
            network_interface: "enX1"
            network_ipv4_address: "192.168.0.17/24"
            network_ipv4_netmask: "255.255.255.0"
            network_ipv4_gateway: "192.168.0.9"
            network_ipv6_address: ""
            network_ipv6_gateway: ""
            network_dns_list: ["200.129.0.41","200.129.0.42"]

      hosts:
        # =========================
        # MÁQUINAS (só editar aqui)
        # =========================

        proxy-ce-01:
          <<: [*proxy_defaults, *profile_pop_ce]
          ansible_host: 192.168.0.17
          # hostnames específicos do Zabbix:
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
          # overrides opcionais só pra este host:
          # ansible_port: 22222

        proxy-as_angolacables-01:
          <<: [*proxy_defaults, *profile_as_angolacables]
          ansible_host: 192.168.0.17
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
