all:
  children:
    proxies:
      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ansible/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
        # 1ยบ run pode usar 22; depois mude para 22222 se sua role trocar a porta
        ansible_port: 22
      hosts:
        proxy-ce-01:
          ansible_host: 192.168.0.17
          location: pop_ce
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
          # rede
          network_interface: "enX1"
          network_ipv4_address: "192.168.0.17/24"
          network_ipv4_netmask: "255.255.255.0"
          network_ipv4_gateway: "192.168.0.9"
          network_ipv6_address: ""
          network_ipv6_gateway: ""
          network_dns_list: ["200.129.0.41","200.129.0.42"]
        proxy-ms-01:
          ansible_host: 192.168.0.17
          location: pop_ms
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
          network_interface: "enX1"
          network_ipv4_address: "192.168.0.17/24"
          network_ipv4_netmask: "255.255.255.0"
          network_ipv4_gateway: "192.168.0.9"
          network_ipv6_address: ""
          network_ipv6_gateway: ""
          network_dns_list: ["200.129.0.41","200.129.0.42"]

        proxy-as_angolacables-01:
          ansible_host: 192.168.0.17
          location: as_angolacables
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
          network_interface: "enX1"
          network_ipv4_address: "192.168.0.17/24"
          network_ipv4_netmask: "255.255.255.0"
          network_ipv4_gateway: "192.168.0.9"
          network_ipv6_address: ""
          network_ipv6_gateway: ""
          network_dns_list: ["200.129.0.41","200.129.0.42"]
