all:
  children:
    proxies:
      hosts:
        ce-pop-teste:
          ansible_host: 192.168.0.238
          ansible_user: ger_adm
          ansible_port: 22222
          ansible_python_interpreter: /usr/bin/python3

          zabbix_proxy_hostname: ce-pop-sv-vm-proxy01

          network_interface: enX1
          network_ipv4_address: 192.168.0.238/24
          network_ipv4_netmask: 255.255.255.0
          network_ipv4_gateway: 192.168.0.9
          network_dns_list: ["1.1.1.1","8.8.8.8"]

          zabbix_server_ip: 192.168.0.208
          zabbix_active_server_ips: ["192.168.0.208"]
