all:
  children:
    proxies:
      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ansible/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
        ansible_port: 22
      hosts:
        proxy-ce-01:
          ansible_host: 192.168.0.17
          # rede
          network_interface: "ens18"
          network_ipv4_address: "192.168.0.17/24"
          network_ipv4_netmask: "255.255.255.0"
          network_ipv4_gateway: "192.168.0.9"
          network_dns_list: ["200.129.0.41","200.129.0.42"]
          # zabbix
          zabbix_proxy_hostname: "ce-zabbix-rnp-ger-proxy01"
          zabbix_agent_hostname: "ce-zabbix-rnp-ger-proxy01"
          # sobrescrita opcional
          # ssh_port: 22222
