# ==============================================================================
# GT Monitoramento 2025
# Variáveis Globais do Projeto
# Arquivo: ansible/group_vars/all.yml
# Descrição: Variáveis globais utilizadas nos roles:
#             - vm_config_setup (roles/vm_config_setup)
#             - zabbix_proxy (roles/zabbix_proxy)
#             - zabbix_agent (roles/zabbix_agent)
#             - (integração API agora é via scripts/ Python)
# ==============================================================================

# ==============================================================================
# Seção I: Configurações de Versão e Repositório Zabbix (Debian 12)
# ==============================================================================
zabbix_version: "7.2"
zabbix_repo_file: "zabbix-release_latest_7.2+debian12_all.deb"
zabbix_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/{{ zabbix_repo_file }}"
zabbix_proxy_package: "zabbix-proxy-sqlite3=1:7.2.7-1+debian12"
zabbix_agent_package: "zabbix-agent2=1:7.2.7-1+debian12"
zabbix_agent_service_name: "zabbix-agent2"

# ==============================================================================
# Seção II: Configurações de Rede (agnóstico)
# ==============================================================================
# evita itens "" nas listas
network_addresses: >-
  {{
    [
      network_ipv4_address | default(''),
      network_ipv6_address | default('')
    ] | reject('equalto','') | list
  }}

network_nameservers: >-
  {{ (network_dns_list | default([])) | reject('equalto','') | list }}

# cria rotas default somente se houver gateway definido
network_routes: >-
  {{
    [
      (network_ipv4_gateway is defined and (network_ipv4_gateway | length) > 0)
        | ternary({'to':'default','via':network_ipv4_gateway,'metric':50}, omit),
      (network_ipv6_gateway is defined and (network_ipv6_gateway | length) > 0)
        | ternary({'to':'default','via':network_ipv6_gateway}, omit)
    ] | reject('equalto', omit) | list
  }}

# ==============================================================================
# Seção III: Configurações do Zabbix Proxy
# ==============================================================================
# ProxyMode: 0=active, 1=passive
zabbix_proxy_mode: 0

zabbix_proxy_buffermode: "hybrid"
zabbix_proxy_memory_buffer_size: "256M"
zabbix_proxy_proxybuffer: 0

### PROXY SERVICE
zabbix_server_port_for_proxy: 10051
zabbix_proxy_listenip: "0.0.0.0"
zabbix_proxy_ip: "{{ (network_ipv4_address | default(ansible_host ~ '/32')) | split('/') | first }}"
zabbix_proxy_pidfile: "/run/zabbix/zabbix_proxy.pid"
zabbix_proxy_socket_dir: "/run/zabbix"

### PROCESSES
zabbix_proxy_startpollers: 550
zabbix_proxy_startpreprocessors: 40
zabbix_proxy_startpollersunreachable: 60
zabbix_proxy_starthistorypollers: 10
zabbix_proxy_starttrappers: 10
zabbix_proxy_startpingers: 100
zabbix_proxy_startdiscoverers: 100
zabbix_proxy_starthttpollers: 10
zabbix_proxy_startsnmppollers: 50
zabbix_proxy_startagentpollers: 50
zabbix_proxy_startdbsyncers: 4
zabbix_proxy_startipmipollers: 1
zabbix_proxy_startvmwarecollectors: 1

### CACHE
zabbix_proxy_cachesize: 512M
zabbix_proxy_historycachesize: 64M
zabbix_proxy_historyindexcachesize: 32M

### TLS (números conforme documentação)
# tls_connect: 1=PSK, 2=Cert
# tls_accept (bitmask): 1=PSK, 2=Cert, 4=None
zabbix_proxy_tls_connect: 1         # PSK (cliente -> server)
zabbix_proxy_tls_accept: 1          # PSK (proxy aceita PSK)
zabbix_proxy_psk_identity: "{{ zabbix_proxy_hostname }}-psk"
zabbix_proxy_psk_file: "/etc/zabbix/psk/{{ zabbix_proxy_hostname }}.psk"

### LOG
zabbix_proxy_logfile: "/var/log/zabbix/zabbix_proxy.log"
zabbix_proxy_logtype: "file"
zabbix_proxy_logfile_size: 5
zabbix_proxy_debug_level: 1

#### LOCAL DATABASE
zabbix_proxy_dbname: "/var/lib/zabbix/zabbix_proxy.db"
zabbix_proxy_offline_buffer: 12

### TIMERS
zabbix_proxy_heartbeat_frequency: 60
zabbix_proxy_config_frequency: 60
zabbix_proxy_datasender_frequency: 1
zabbix_proxy_housekeeping_frequency: 1
zabbix_proxy_timeout: 15
zabbix_proxy_trappertimeout: 300
zabbix_proxy_unreachable_period: 45
zabbix_proxy_unavailable_delay: 60
zabbix_proxy_unreachable_delay: 15

### FPING
zabbix_proxy_fping_location: "/usr/bin/fping"
zabbix_proxy_fping6_location: "/usr/bin/fping6"

### REMOTE COMMANDS
zabbix_proxy_enable_remote_commands: 0
zabbix_proxy_log_remote_commands: 0

### DATABASE COMPATIBILITY
zabbix_proxy_allow_unsupported_db: 0

### SSH
zabbix_proxy_ssh_key_location: "/etc/zabbix/ssh_keys/.ssh"

# ==============================================================================
# Seção IV: Configurações do Zabbix Agent (Agent2)
# ==============================================================================
zabbix_agent_pidfile: "/run/zabbix/zabbix_agent2.pid"
zabbix_agent_logtype: "file"
zabbix_agent_logfile: "/var/log/zabbix/zabbix_agent2.log"
zabbix_agent_logfile_size: 5
zabbix_agent_debug_level: 1
zabbix_agent_source_ip: "{{ (network_ipv4_address | default(ansible_default_ipv4.address ~ '/32')) | split('/') | first }}"

# PASSIVE
zabbix_agent_server: "{{ zabbix_server_ip }}"
zabbix_agent_listenport: 10050

# ACTIVE
zabbix_agent_serveractive_list: "{{ zabbix_active_server_ips }}"
zabbix_agent_hostname: "{{ zabbix_proxy_hostname }}"
zabbix_agent_refresh_active_checks: 300
zabbix_agent_buffer_send: 10
zabbix_agent_buffer_size: 100
zabbix_agent_enable_persistent_buffering: 0
zabbix_agent_persistent_buffer_period: 1h
zabbix_agent_persistent_buffer_file: "/var/lib/zabbix/agent2/persistent_buffer"

# ADVANCED
zabbix_agent_include_dir: "/etc/zabbix/zabbix_agent2.d/*.conf"
zabbix_agent_timeout: 30
zabbix_agent_unsafe_user_parameters: 0
zabbix_agent_control_socket: "/tmp/agent.sock"

# TLS
zabbix_agent_tls_connect: "psk"
zabbix_agent_tls_accept: "psk"
zabbix_agent_psk_identity: "{{ zabbix_agent_hostname }}-psk-agent"
zabbix_agent_psk_file: "/etc/zabbix/psk/{{ zabbix_agent_hostname }}-agent.psk"

# PLUGINS
zabbix_agent_plugins_log_max_lines: 20
zabbix_agent_plugins_docker_endpoint: "unix:///var/run/docker.sock"
zabbix_agent_plugins_docker_timeout: 20

# ==============================================================================
# Seção V: Segurança (UFW / Fail2ban / SSH)
# ==============================================================================
# Porta SSH padrão (usada em vm_config_setup e nas regras)
ssh_port: 22222

# Fail2Ban — montar lista final sem elementos vazios e sem listas-virarem-strings
_fail2ban_ignore_sources: >-
  {{
    [
      "127.0.0.1/8",
      network_ipv4_gateway | default('')
    ]
    + (zabbix_active_server_ips | default([]))
    + (network_addresses | default([]))
  }}
fail2ban_ignore_ips: "{{ _fail2ban_ignore_sources | reject('equalto','') | list }}"

# UFW
ufw_rules:
  - rule: allow
    from: ["{{ network_ipv4_gateway | default('') }}"]
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH - Gateway IPv4"
    direction: in

  - rule: allow
    from: "{{ network_addresses }}"
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH - IPs da localidade"
    direction: in

  - rule: allow
    from: ["{{ network_ipv4_gateway | default('') }}"]
    port: 10050
    proto: tcp
    comment: "Zabbix Agent - Gateway"
    direction: in

  - rule: allow
    from: ["{{ network_ipv4_gateway | default('') }}"]
    port: 10051
    proto: tcp
    comment: "Zabbix Proxy - Gateway"
    direction: in

  - rule: allow
    from: "{{ zabbix_active_server_ips }}"
    port: 10050
    proto: tcp
    comment: "Zabbix Agent - Active Servers"
    direction: in

  - rule: allow
    from: "{{ zabbix_active_server_ips }}"
    port: 10051
    proto: tcp
    comment: "Zabbix Proxy - Active Servers"
    direction: in

# ==============================================================================
# Seção VI: Registro de Host na API (grupos/templates)
# ==============================================================================
zabbix_agent_hostgroups:
  - "Linux servers"
  - "Zabbix proxies"

zabbix_agent_templates:
  - "Linux by Zabbix agent"

# ==============================================================================
# Seção VII: Sistema/VM (vm_config_setup)
# ==============================================================================
vm_timezone: "America/Fortaleza"
vm_hostname: "{{ zabbix_proxy_hostname | default(inventory_hostname) }}"

# Usuário administrativo da VM
vm_admin_user: "ger_adm"
vm_admin_shell: "/bin/bash"
vm_admin_groups:
  - "sudo"

# Senha do usuário admin:
# - Se DEFINIR texto em vm_admin_password, a role fará o HASH (sha512) e aplicará.
# - Se deixar vazio, a role GERARÁ uma senha forte e salvará em:
#     - /root/.{{ vm_admin_user }}.passwd (no host, root-only)
#     - artifacts/credentials/{{ inventory_hostname }}.{{ vm_admin_user }}.passwd (no runner)
vm_admin_password: ""
