# /ansible/playbooks/provision.yml
- name: Provisionar base da VM + Zabbix Proxy e Agent2 (Debian 12)
  hosts: proxies
  become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: pre_configs        # valida/normaliza variáveis 
    - role: vm_config_setup    # rede, SSH, UFW, Fail2Ban, MOTD...
    - role: zabbix_proxy       # instala/configura Zabbix Proxy
    - role: zabbix_agent       # instala/configura Zabbix Agent
    - role: artifacts          # salva PSK p/ pipeline
