# ==============================================================================
# Tasks da Role 'zabbix_agent' 
# Arquivo: roles/zabbix_agent/tasks/main.yml
# Descrição: Realiza a instalação e configuração do Zabbix Agent 2.
# ==============================================================================
---
# --- Instalação do Zabbix Agent 2 ---
- name: Instalar Zabbix Agent2
  ansible.builtin.apt:
    name: "{{ zabbix_agent_package }}"
    state: present
    update_cache: yes

# --- Diretórios necessários ---
- name: Garantir /run/zabbix existe (PID/Socket)
  ansible.builtin.file:
    path: /run/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Garantir diretório do PSK existe
  ansible.builtin.file:
    path: "{{ zabbix_agent_psk_file | dirname }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

# --- PSK: gerar somente se não existir (sem vazar em log) ---
- name: Verificar se o PSK do agente já existe
  ansible.builtin.stat:
    path: "{{ zabbix_agent_psk_file }}"
  register: agent_psk_file_status
  changed_when: false

- name: Gerar PSK do agente (somente se não existir)
  ansible.builtin.command: openssl rand -hex 32
  register: agent_psk_value
  when: not agent_psk_file_status.stat.exists
  changed_when: true
  no_log: true

- name: Criar arquivo PSK com permissões seguras
  ansible.builtin.copy:
    # Adicionado | trim para remover a quebra de linha no final da chave gerada pelo openssl.
    # Isso garante que a chave no arquivo seja idêntica à enviada para a API.
    content: "{{ agent_psk_value.stdout | trim }}"
    dest: "{{ zabbix_agent_psk_file }}"
    owner: zabbix
    group: zabbix
    mode: '0600'
  when: not agent_psk_file_status.stat.exists
  no_log: true

# --- Expor PSK como fato para outros roles (ex.: registro via API) ---
- name: Ler PSK do agente do disco
  ansible.builtin.slurp:
    src: "{{ zabbix_agent_psk_file }}"
  register: agent_psk_file_content
  changed_when: false
  no_log: true

- name: Definir fato com o valor da PSK
  ansible.builtin.set_fact:
    agent_psk_key: "{{ (agent_psk_file_content.content | b64decode) | trim }}"
    cacheable: true
  no_log: true

# --- Configuração e serviço ---
- name: Aplicar configuração do Zabbix Agent2
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Zabbix Agent

- name: Habilitar e iniciar Zabbix Agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
    state: restarted
    daemon_reload: yes